plugins {
    id 'java'
}

group = 'org.example'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
    maven {
        url "http://packages.confluent.io/maven"
        allowInsecureProtocol true
    }
}

dependencies {
    testImplementation platform('org.junit:junit-bom:6.0.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
    implementation 'org.apache.kafka:kafka-clients:8.3.0-ce'
    implementation 'org.apache.kafka:kafka-streams:8.3.0-ce'
    implementation 'org.apache.kafka:kafka-streams-test-utils:8.3.0-ce'
    testImplementation "org.testcontainers:testcontainers:2.0.5"
    testImplementation "org.testcontainers:testcontainers-junit-jupiter:2.0.5"
    testImplementation('org.testcontainers:testcontainers-kafka:2.0.5')
    implementation 'org.slf4j:slf4j-api:2.0.17'
    implementation 'ch.qos.logback:logback-classic:1.5.36'
}

test {
    useJUnitPlatform()
}